### ISSUE TITLE
Need smarter installation script that can handle different python 2,3 environments

### ISSUE THREAD

**Issue by cuchaz** [donaldlab/OSPREY3#111]
Current installation scripts are dumb and blindly call either `pip2` or `pip3`. But some platforms (specifically Windows) only have `pip` and don't provide versioned aliases.

Need to update the installation scripts to use the correction python/pyp invocation, even on Windows platforms. Maybe the installation scripts should themselves be written in python?

**Comment by Clint-Holt** [comment]
What would work for people who are using virtual environments is using "python -m pip install ..." and then the correct pip will be used depending on which virtual environment is active. People who are using anaconda have to do this anyway because it only comes with "pip" and not "pip2" or "pip3"

**Comment by gusennan** [comment]
In python 3, pip is a module and can be invoked as 

`python -m pip`

**Comment by Clint-Holt** [comment]
It is a module in python 2 as well and so this way the correct osprey package will be installed for whichever active python interpreter the user is using. It also is considered a little better practice to use "python -m pip install" instead of "pip install" because "pip install" can call the system executable and install osprey system-wide instead of in your active virtual environment.
