### ISSUE TITLE
Azure CI not writing build number correctly?

### ISSUE THREAD

**Issue by cuchaz** [donaldlab/OSPREY3#137]
Latest CI build (172) has a `/config/version` file in it that says `3.2-dev` instead of `3.2.172`. And Osprey's preamble prints out:
```
OSPREY 3.2-dev, Python 3.7.9, Java 14.0.1, Linux-4.15.0-112-generic-x86_64-with-debian-10.5
Using up to 1024 MiB heap memory: 128 MiB for garbage, 896 MiB for storage
```

**Comment by gusennan** [comment]
Should we have [major].[minor].[build-number] everywhere? I think the `dev` tag makes sense for non-azure CI builds.

**Comment by cuchaz** [comment]
No, having build numbers for builds done manually doesn't make sense. But I would expect that when built by Azure, that build of Osprey displays the build number. As far as I could tell, that didn't happen in the case I cited above. I was talking about the build I downloaded from the Azure build system.

**Comment by gusennan** [comment]
I *think* the issue is [`appendBuildNumber`](https://github.com/donaldlab/OSPREY3/blob/master/build.gradle.kts#L420) isn't a dependency of the `assemble` gradle task.  

[Here's](https://github.com/donaldlab/OSPREY3/blob/master/azure-pipelines.yml#L103) where the variable, which should be used by `assembleBuildNumber`, is set.
